services:
  # Frontend: Angular
  angular:
    build:
      context: ./market-league-front-end  # Path to your Angular project directory
      dockerfile: Dockerfile.dev
    container_name: angular-dev
    ports:
      - 4200:4200  # Map port 4200 for Angular dev server
    volumes:
      - ./market-league-front-end:/app  # Map local directory to container for live-reload
      - /app/node_modules  # Avoid overwriting node_modules with local one
    command: ng serve --host 0.0.0.0 

  # Backend: Gin (Go)
  gin-backend:
    build:
        context: ./market-league-back-end
        dockerfile: Dockerfile.dev
    ports:
        - 9000:9000
    restart: unless-stopped
    expose:
        - 9000
    command: ./main
    depends_on:
      db:
        condition: service_healthy

  # Database: PostgreSQL
  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_USER: postgres       # Creates the "postgres" user (default superuser)
      POSTGRES_PASSWORD: yourpassword   # Sets the password for the "postgres" user
      POSTGRES_DB: yourdatabase     # Creates a default database named "yourdatabase"
    ports:
      - 5432:5432   # Exposes PostgreSQL on port 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data   # Persists database data

  # Database Manager
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    expose:
      - 8080

# Volume for Postegres database
volumes:
  postgres_data: