# docker-compose - Production

services:
  # Angular Frontend Service
  frontend:
    build:
      context: ./market-league-front-end  # Path to your Angular project directory
      dockerfile: Dockerfile.prod  # Production Dockerfile for Angular (Docker.prod)
    container_name: angular-prod
    ports:
      - "80:80"  # Serve on port 80 (HTTP)
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf  # Mount the server block in the correct location
    networks:
      - market-league-network

  # Gin Backend Service
  backend:
    build:
      context: ./market-league-back-end  # Path to your Gin project directory
      dockerfile: Dockerfile.prod  # Production Dockerfile for Gin (Docker.prod)
    container_name: gin-prod
    ports:
      - "5000:5000"  # Expose the Gin API on port 5000
    depends_on:
      - db
    networks:
      - market-league-network

  # PostgreSQL Database Service
  db:
    image: postgres:13  # Use a stable version of PostgreSQL
    container_name: postgres-prod
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  # Fetch from the .env file
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Fetch from the .env file
      POSTGRES_DB: ${POSTGRES_DB}  # Fetch from the .env file
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist PostgreSQL data
    networks:
      - market-league-network

# Networks
networks:
  market-league-network:
    driver: bridge

# Volumes for PostgreSQL persistence
volumes:
  pgdata: