name: MarketLeague CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy MarketLeague
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DROPLET_SSH_KEY }}

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_IP }} << 'EOF'
          cd /home/market-league
          git pull origin main
          docker compose -f docker-compose.prod.yml up --build -d
        EOF
